### ISSUE TITLE
Responsive Off-Canvas breaks silently in FF Aurora (38.0a2 (2015-03-10))

### ISSUE THREAD

**Issue by michapixel** [n33/skel-layers#17]
see:
http://i.imgur.com/YR9yNXM.png

the html-class 'small' doesn't get attached - as far as i can see, so this might be related to skel itself.

**Comment by n33** [comment]
Can't reproduce that in FF (regular release, not Aurora) nor any other browser, so it's possible something's broken in that build you're using.
